from __future__ import annotations

import argparse
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "src" / "_version_generated.py"
DEFAULT_VERSION = "0.0.0"


def current_version() -> str:
    try:
        result = subprocess.run(
            ["git", "describe", "--tags", "--dirty", "--always"],
            cwd=ROOT,
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return DEFAULT_VERSION
    version = result.stdout.strip()
    return version or DEFAULT_VERSION


def write_version(path: Path = OUTPUT) -> str:
    version = current_version()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "# Generated by scripts/write_version.py; do not edit.\n"
        f"VERSION = {version!r}\n",
        encoding="utf-8",
    )
    return version


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate src/_version_generated.py from git tags")
    parser.add_argument("--print", action="store_true", help="Print the detected version")
    args = parser.parse_args()

    version = write_version()
    if args.print:
        print(version)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
